In [151]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
sp.init_printing(use_unicode=True)

# Matrix Variansi dan Matrix Regresi

In [37]:
# create matrix covariance function
def matrix_variansi(mat):
    nrow = mat.shape[0]
    ncol = mat.shape[1]
    row_means = mat.mean(axis=1)[:, np.newaxis] 
    s_mat = np.zeros((nrow, nrow))
    A = mat-row_means
    for row1 in range(nrow):
        for row2 in range(nrow):
            s_mat[row1,row2]= (np.sum(A[row1,:]*A[row2,:]))/ncol
            
    return s_mat

In [32]:
# create matrix r correlation function
def matrix_r(mat):
    nrow = mat.shape[0]
    mat_var = matrix_variansi(mat)
    r_mat = np.zeros((nrow, nrow))
    for row in range(nrow):
        for col in range(nrow):
            r_mat[row,col] = (mat_var[row,col])/((np.sqrt(mat_var[row,row]))*(np.sqrt(mat_var[col,col])))
            r_mat[row,col] = np.round(r_mat[row,col],2)
    return r_mat

array([[ 1.  , -0.87,  0.  ],
       [-0.87,  1.  ,  0.5 ],
       [ 0.  ,  0.5 ,  1.  ]])

In [39]:
mat_modul_2_contoh_2_2 = np.array([[1,4,4],
                [2,1,0],
                [5,6,4]])


In [40]:
matrix_variansi(mat=mat_modul_2_contoh_2_2)

array([[ 2.        , -1.        ,  0.        ],
       [-1.        ,  0.66666667,  0.33333333],
       [ 0.        ,  0.33333333,  0.66666667]])

In [41]:
matrix_r(mat=mat_modul_2_contoh_2_2)

array([[ 1.  , -0.87,  0.  ],
       [-0.87,  1.  ,  0.5 ],
       [ 0.  ,  0.5 ,  1.  ]])

In [ ]:
mat_modul_2_tesformatif_1_no_1 = np.array([[42,52,48,58],
                                          [4,5,4,3]])

In [42]:
matrix_variansi(mat=mat_modul_2_tesformatif_1_no_1)

array([[34. , -1.5],
       [-1.5,  0.5]])

In [43]:
matrix_r(mat=mat_modul_2_tesformatif_1_no_1)

array([[ 1.  , -0.36],
       [-0.36,  1.  ]])

# Jarak

In [155]:
# Create jarak euclidian

def euclidian(mat, P, Q, teta, a11, a22, a12):   
    nrow = mat.shape[0]
    mat_var = matrix_variansi(mat)
    
    def a(teta):        
        pembilang_1 = (np.cos(teta))**2*mat_var[0,0] + 2*np.sin(teta)*np.cos(teta)*mat_var[0,1] + (np.sin(teta))**2*mat_var[1,1]
        pembilang_2 = (np.cos(teta))**2*mat_var[1,1] - 2*np.sin(teta)*np.cos(teta)*mat_var[0,1] + (np.sin(teta))**2*mat_var[0,0]
        a11 = (((np.cos(teta))**2)/pembilang_1)+(((np.sin(teta))**2)/pembilang_2)
        a22 = (((np.sin(teta))**2)/pembilang_1)+(((np.cos(teta))**2)/pembilang_2)
        a12 = ((np.cos(teta)*np.sin(teta))/pembilang_1)+((np.cos(teta)*np.sin(teta))/pembilang_2)
        return a11, a22, a12
    
    if a11 > 1:
        print(a11 != 0)
        a11, a22, a12 = a(teta=teta)
        dPQ_jarak_statistik = np.sqrt(a11*((P[0]-Q[0])**2) + 2*a12*(P[0]-Q[0])*(P[1]-Q[1])) + a22*((P[1]-Q[1])**2)
        print(f"d(P,Q) Jarak Statistik = {dPQ_jarak_statistik}")
    else:
        dPQ_jarak_statistik = np.sqrt(a11*((P[0]-Q[0])**2) + 2*a12*(P[0]-Q[0])*(P[1]-Q[1])) + a22*((P[1]-Q[1])**2)
        print(f"d(P,Q) Jarak Statistik = {dPQ_jarak_statistik}")
    
    dPQ_euclidian = np.sqrt(((P[0]-Q[0])**2)+((P[1]-Q[1])**2))
    
    
    print(f"d(P,Q) Euclidian = {dPQ_euclidian}")
   

P = np.array([-1, -1])
Q = np.array([1, 0])
mat = np.array([[2,3,4], [1,2,4]])
euclidian(mat=mat, P=P, Q=Q, teta=0, a11 = 1/3, a22=4/27, a12=1/9)


d(P,Q) Jarak Statistik = 1.4814814814814814
d(P,Q) Euclidian = 2.23606797749979


In [156]:

print((2/3)*np.sqrt(13/3)) 

1.3877773329774217
