In [47]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp
sp.init_printing(use_unicode=True)

# KEGIATAN BELAJAR 1

In [35]:
# create matrix covariance function
def matrix_variansi(mat, ket):
    nrow = mat.shape[0]
    ncol = mat.shape[1]
    row_means = mat.mean(axis=1)[:, np.newaxis]
    if ket == True:
        print(f"Row mean:")
        print(row_means) 
    s_mat = np.zeros((nrow, nrow))
    A = mat-row_means
    for row1 in range(nrow):
        for row2 in range(nrow):
            s_mat[row1,row2]= (np.sum(A[row1,:]*A[row2,:]))/ncol
    if ket == True:        
        print("")
        print("Matrix Variansi:")            
    return s_mat

In [36]:
# create matrix r correlation function
def matrix_r(mat):
    nrow = mat.shape[0]
    mat_var = matrix_variansi(mat, ket=False)
    r_mat = np.zeros((nrow, nrow))
    for row in range(nrow):
        for col in range(nrow):
            r_mat[row,col] = (mat_var[row,col])/((np.sqrt(mat_var[row,row]))*(np.sqrt(mat_var[col,col])))
            r_mat[row,col] = np.round(r_mat[row,col],2)
    return r_mat

## Contoh 2.2

In [4]:
mat_modul_2_contoh_2_2 = np.array([[1,4,4],
                [2,1,0],
                [5,6,4]])


In [37]:
matrix_variansi(mat=mat_modul_2_contoh_2_2, ket=False)

array([[ 2.        , -1.        ,  0.        ],
       [-1.        ,  0.66666667,  0.33333333],
       [ 0.        ,  0.33333333,  0.66666667]])

In [39]:
matrix_r(mat=mat_modul_2_contoh_2_2)

array([[ 1.  , -0.87,  0.  ],
       [-0.87,  1.  ,  0.5 ],
       [ 0.  ,  0.5 ,  1.  ]])

## Tes Formatif 1 No.1

In [7]:
mat_modul_2_tesformatif_1_no_1 = np.array([[42,52,48,58],
                                          [4,5,4,3]])

In [8]:
matrix_variansi(mat=mat_modul_2_tesformatif_1_no_1)

array([[34. , -1.5],
       [-1.5,  0.5]])

## Tes Formatif 1 No. 2

In [9]:
matrix_r(mat=mat_modul_2_tesformatif_1_no_1)

array([[ 1.  , -0.36],
       [-0.36,  1.  ]])

# Jarak

In [26]:
# Create jarak euclidian

def euclidian(mat, P, Q, teta, a11, a22, a12):   
    nrow = mat.shape[0]
    mat_var = matrix_variansi(mat)
    # print("check 1")
    
    def a(teta):        
        pembilang_1 = (np.cos(teta))**2*mat_var[0,0] + 2*np.sin(teta)*np.cos(teta)*mat_var[0,1] + (np.sin(teta))**2*mat_var[1,1]
        pembilang_2 = (np.cos(teta))**2*mat_var[1,1] - 2*np.sin(teta)*np.cos(teta)*mat_var[0,1] + (np.sin(teta))**2*mat_var[0,0]
        a11 = (((np.cos(teta))**2)/pembilang_1)+(((np.sin(teta))**2)/pembilang_2)
        a22 = (((np.sin(teta))**2)/pembilang_1)+(((np.cos(teta))**2)/pembilang_2)
        a12 = ((np.cos(teta)*np.sin(teta))/pembilang_1)+((np.cos(teta)*np.sin(teta))/pembilang_2)
        return a11, a22, a12
    # print("check 2")
    if teta > 0:
        print(a11 <= 0)
        a11, a22, a12 = a(teta=teta)
        print(a11, a22, a12)
        dPQ_jarak_statistik = np.sqrt(a11*((P[0]-Q[0])**2) + 2*a12*(P[0]-Q[0])*(P[1]-Q[1])) + a22*((P[1]-Q[1])**2)
        print(f"d(P,Q) Jarak Statistik = {dPQ_jarak_statistik}")
    else:
        # print("check 3")
        dPQ_jarak_statistik = np.sqrt(a11*((P[0]-Q[0])**2) + 2*a12*(P[0]-Q[0])*(P[1]-Q[1])) + a22*((P[1]-Q[1])**2)
        print(f"d(P,Q) Jarak Statistik = {dPQ_jarak_statistik}")
    
    dPQ_euclidian = np.sqrt(((P[0]-Q[0])**2)+((P[1]-Q[1])**2))
    
    
    print(f"d(P,Q) Euclidian = {dPQ_euclidian}")
   




## Contoh 2.4

In [11]:

P = np.array([-1, -1])
Q = np.array([1, 0])
mat = np.array([[2,3,4], [1,2,4]])
euclidian(mat=mat, P=P, Q=Q, teta=0, a11 = 1/3, a22=4/27, a12=1/9)

d(P,Q) Jarak Statistik = 1.4814814814814814
d(P,Q) Euclidian = 2.23606797749979


In [12]:
(2/3)*np.sqrt((13/3))

In [13]:
np.sqrt(5)

## Tes Formatif 1 Soal 4

In [14]:
P = np.array([1, 1])
Q = np.array([0, 0])
mat = np.array([[42,52,48,58], [4,5,4,3]])
euclidian(mat=mat, P=P, Q=Q, teta=0, a11 = 1/3, a22=4/27, a12=1/9)

d(P,Q) Jarak Statistik = 0.893504140648078
d(P,Q) Euclidian = 1.4142135623730951


In [18]:
# Jawaban A
np.sqrt(19/27)

## Tes Formatif 1 Soal 5

In [27]:
P = np.array([4, -2])
Q = np.array([0, 0])
mat = np.array([[-6,-3,-2,1,2,5,6,8], [-2,-3,1,-1,2,1,5,3]])
euclidian(mat=mat, P=P, Q=Q, teta=26, a11=0, a22=0, a12=0)

True
0.12496741841844079 0.10319674102903198 0.11255652761280069
d(P,Q) Jarak Statistik = 0.8584036748555723
d(P,Q) Euclidian = 4.47213595499958


## Tes Formatif 1 Soal 6

In [40]:
mat = np.array([[42,26,52,60,48,50,58],
                [4,2,5,6,4,5,3]])

matrix_variansi(mat=mat, ket=True)

Row mean:
[[48.        ]
 [ 4.14285714]]

Matrix Variansi:


array([[112.        ,   9.14285714],
       [  9.14285714,   1.55102041]])

In [41]:
matrix_r(mat=mat)

array([[1.  , 0.69],
       [0.69, 1.  ]])

# KEGIATAN BELAJAR 2

In [56]:
def matrix_E_dikrit(X1, X2):
    EX1=0
    for i in range(len(X1[0,:])):
        EX1 += X1[0,i]*X1[1,i]
    EX2 = 0
    for i in range(len(X2[0,:])):
        EX2 += X2[0,i]*X2[1,i]        
    
    return np.array([EX1, EX2])    

def matrix_kovariansi(mat_prob):
    df = pd.DataFrame(mat_prob, columns=["X1", "X2", "Probability"])
    cross_tab = pd.crosstab(df['X1'], df['X2'], values=df['Probability'], aggfunc='sum')
    cross_tab['p1(x1)'] = cross_tab.sum(axis=1)    
    cross_tab = pd.crosstab(df['X1'], df['X2'], values=df['Probability'], aggfunc='sum', margins=True, margins_name='Total')
    return cross_tab.loc['Total', 0]  


mat_prob = np.array([
    [-1, 0, 0.24],
    [-1, 1, 0.06],
    [0, 0, 0.16],
    [0, 1, 0.14],
    [1, 0 , 0.4,],
    [1, 1, 0.00]
])

matrix_kovariansi(mat_prob=mat_prob)


## Contoh 2.5

In [46]:
X1 = np.array([
    [-1, 0, 1],
    [0.3, 0.3, 0.4]
])
X2 = np.array([
    [0, 1],
    [0.8, 0.2]
])

matrix_E_dikrit(X1=X1, X2=X2)


array([0.1, 0.2])

## Contoh 2.6